### ISSUE TITLE
Issue on training

### ISSUE THREAD

**Issue by Mathreyu** [isseu/emotion-recognition-neural-networks#1]
Hello, I was trying to use this app as a base to understand how to make my own emotion recognition software, but the training part seems kind of unexplained. I downloaded the .csv and tried to run the training, but the program didnt seem to find the the file. 

Can you please clarify this, or give a more in depth explanation? 

Thanks.

**Comment by isseu** [comment]
Hello!

We use the script that is in `data/cvs_to_numpy.py` to transform the .cvs to a numpy array file

**Comment by Mathreyu** [comment]
Hi there again :D 
the thing is: I've tried to convert the data into a numpy array but it always displays the error message, beacuse it doesn't find any "faces", hence the issue :/

**Comment by Mathreyu** [comment]
` # None is we don't found an image
  if not len(faces) > 0:
    return None`

Apparently the convertion to numpy array is getting stuck there. (just extra fb :))

**Comment by nimish1512** [comment]
If it shows something like "slicing indices must be Integer or None", change line no 20 to this:
gray_border[(int(150 / 2) - int(SIZE_FACE/2)):(int(150/2)+int(SIZE_FACE/2)), (int(150/2)-int(SIZE_FACE/2)):(int(150/2)+int(SIZE_FACE/2))] = image

**Comment by kerrywang** [comment]
I am running into the same problem. Always returning error
Progreso: 1711/35887 4.77%
Error
Progreso: 1712/35887 4.77%
Error

Can anyone please help me fix the issue?

**Comment by wonny2001** [comment]
i think it came from CASC_PATH 
copy constants.py to ./data and change
CASC_PATH = '../haarcascade_files/haarcascade_frontalface_default.xml'

**Comment by Sarvin92** [comment]
@wonny2001 Even after doing the changes you said, I get the sample result as follows:
Progreso: 35882/35887 99.99%
Error
Progreso: 35883/35887 99.99%
Error
Progreso: 35884/35887 99.99%
Error
Progreso: 35885/35887 99.99%
(48, 48)
Progreso: 35886/35887 100.00%
(48, 48)
Progreso: 35887/35887 100.00%
Total: 13974
