### ISSUE TITLE
Issue with python emotion_recognition.py train

### ISSUE THREAD

**Issue by ghost** [isseu/emotion-recognition-neural-networks#3]
Hey,

I'm trying to replicate the training process. I ran the cvs_to_numpy.py script and have the data_kike.npy and labels_kike.npy files within the data folder. When I run python emotion_recognition.py I get "IOError: [Errno 2] No such file or directory: './data/data_set_fer2013.npy'".

How do I go about getting that file/the other files in the constants.py.

**Comment by mysayalHan** [comment]
For convenience, I just make data_kike as train and test data, similarly, make labels_kike into train and test label.

**Comment by NikAndrush** [comment]
@mysayalHan how you do it?
