### ISSUE TITLE
why my predict always are angry

### ISSUE THREAD

**Issue by xhjcxxl** [isseu/emotion-recognition-neural-networks#38]
I'm sorry,I train the network of fer2013,then I use the pro to predict my picture and my video.But In my screen, it's always tell me its angry, although the pciture is not right emothion's picture.
So, please help me.

**Comment by isseu** [comment]
Sorry but the FER-2013 dataset is not of good enough quality to be used with other applications. I recommend you start looking for other alternatives of dataset.

**Comment by isseu** [comment]
The dataset is of very bad quality and the images are very different from images you would get from your webcam. That why the performance is very bad.

**Comment by xhjcxxl** [comment]
thanks, I  found it . On the other hand, the model not load in the predict.

**Comment by snowalala** [comment]
@xhjcxxl Hi, I have the same problem as you. Do you know how to load the model in predict? Thank you.
