### ISSUE TITLE
How to solve the problem about data_set_fer2013.npy etc.

### ISSUE THREAD

**Issue by xhjcxxl** [isseu/emotion-recognition-neural-networks#39]
When we run the csv_to_numpy.py,it will output two files which are the data_kike.npy and labels_kike.npy.
But we dont need these files. So, we should output:
    data_set_fer2013.npy
    data_labels_fer2013.npy
    test_set_fer2013.npy
    test_labels_fer2013.npy

1. we open file which name is fer2013.csv, we will found the Usage have three type:
    **Training**(this is train set)
    **PublicTest**(this is test set)
    **PrivateTest**(not used)
2. we should change our code as below:
     Usage = row['Usage']
    if image is not None:
        print(Usage)
        if Usage == "**Training**":
            labels.append(emotion)
            images.append(image)
            index_set += 1
        elif Usage == "**PublicTest**":
            labels_test.append(emotion)
            images_test.append(image)
            index_test += 1
then we will get four data:
    labels
    images
    labels_test
    images_test
then we can save it:
    np.save('data_set_fer2013.npy', images)
    np.save('data_labels_fer2013.npy', labels)
    np.save('test_set_fer2013.npy', images_test)
    np.save('test_labels_fer2013.npy', labels_test)

3. we also to change the code:
        self._images_test = self._images.reshape([-1, SIZE_FACE, SIZE_FACE, 1])
        self._labels_test = self._labels.reshape([-1, len(EMOTIONS)])
change the code that we need:
      self._labels_test = self.**_labels_test**.reshape([-1, len(EMOTIONS)])
      self._labels_test = self.**_labels_test**.reshape([-1, len(EMOTIONS)])

at last,thanks
atulapra https://github.com/isseu/emotion-recognition-neural-networks/issues/17
dearhoper  https://github.com/isseu/emotion-recognition-neural-networks/issues/6

**Comment by immanikant** [comment]
above mentions changes are done in which file...??

**Comment by xhjcxxl** [comment]
csv_to_numpy.py

**Comment by isseu** [comment]
I fix this problem now.
