### ISSUE TITLE
cvs_to_numpy

### ISSUE THREAD

**Issue by immanikant** [isseu/emotion-recognition-neural-networks#40]
[ INFO:0] Initialize OpenCL runtime...
Traceback (most recent call last):
  File "cvs_to_numpy.py", line 72, in <module>
    image = data_to_image(row['pixels'])
  File "cvs_to_numpy.py", line 60, in data_to_image
    data_image = format_image(data_image)
  File "cvs_to_numpy.py", line 43, in format_image
    print %image.shape
TypeError: unsupported operand type(s) for %: 'builtin_function_or_method' and 'tuple'

**Comment by immanikant** [comment]
i'm getting this erroe after replacing %image.shape with image.shape in cvs_to_numpy.py file i get this error 
[ INFO:0] Initialize OpenCL runtime...
(48, 48)
Progreso: 1/416 0.24%
Error
Progreso: 2/416 0.48%
(48, 48)
Progreso: 3/416 0.72%
Error
Progreso: 4/416 0.96%
(48, 48)
Progreso: 5/416 1.20%
(48, 48)
Progreso: 6/416 1.44%
Error
Progreso: 7/416 1.68%
(48, 48)
Progreso: 8/416 1.92%
(48, 48)
Progreso: 9/416 2.16%
(48, 48)
Progreso: 10/416 2.40%
(48, 48)
Progreso: 11/416 2.64%
Error
Progreso: 12/416 2.88%
Error
Progreso: 13/416 3.12%
Error
Progreso: 14/416 3.37%
(48, 48)
Progreso: 15/416 3.61%
(48, 48)
Progreso: 16/416 3.85%
Error
Progreso: 17/416 4.09%
Error
Progreso: 18/416 4.33%
Error
Progreso: 19/416 4.57%
Error
Progreso: 20/416 4.81%
Error
Progreso: 21/416 5.05%
Error
Progreso: 22/416 5.29%
(48, 48)
Progreso: 23/416 5.53%
Error
Progreso: 24/416 5.77%
Error
Progreso: 25/416 6.01%
(48, 48)
Progreso: 26/416 6.25%
Error
Progreso: 27/416 6.49%
Error
Progreso: 28/416 6.73%
Error
Progreso: 29/416 6.97%
Error
Progreso: 30/416 7.21%
(48, 48)
Progreso: 31/416 7.45%
Error
Progreso: 32/416 7.69%
Error
Progreso: 33/416 7.93%
(48, 48)
Progreso: 34/416 8.17%
Error
Progreso: 35/416 8.41%
(48, 48)
Progreso: 36/416 8.65%
(48, 48)
Progreso: 37/416 8.89%
(48, 48)
Progreso: 38/416 9.13%
(48, 48)
Progreso: 39/416 9.38%
Error
Progreso: 40/416 9.62%
(48, 48)
Progreso: 41/416 9.86%
(48, 48)
Progreso: 42/416 10.10%
Error
Progreso: 43/416 10.34%
Error
Progreso: 44/416 10.58%
Error
Progreso: 45/416 10.82%
Error
Progreso: 46/416 11.06%
(48, 48)
Progreso: 47/416 11.30%
Error
Progreso: 48/416 11.54%
Error
Progreso: 49/416 11.78%
Error
Progreso: 50/416 12.02%
(48, 48)
Progreso: 51/416 12.26%
(48, 48)
Progreso: 52/416 12.50%
(48, 48)
Progreso: 53/416 12.74%
(48, 48)
Progreso: 54/416 12.98%
Error
Progreso: 55/416 13.22%
Error
Progreso: 56/416 13.46%
(48, 48)
Progreso: 57/416 13.70%
Error
Progreso: 58/416 13.94%
(48, 48)
Progreso: 59/416 14.18%
Error
Progreso: 60/416 14.42%
(48, 48)
Progreso: 61/416 14.66%
Error
Progreso: 62/416 14.90%
(48, 48)
Progreso: 63/416 15.14%
(48, 48)
Progreso: 64/416 15.38%
Error
Progreso: 65/416 15.62%
Error
Progreso: 66/416 15.87%
Error
Progreso: 67/416 16.11%
(48, 48)
Progreso: 68/416 16.35%
Error
Progreso: 69/416 16.59%
(48, 48)
Progreso: 70/416 16.83%
Error
Progreso: 71/416 17.07%
(48, 48)
Progreso: 72/416 17.31%
Error
Progreso: 73/416 17.55%
(48, 48)
Progreso: 74/416 17.79%
Error
Progreso: 75/416 18.03%
Error
Progreso: 76/416 18.27%
Error
Progreso: 77/416 18.51%
(48, 48)
Progreso: 78/416 18.75%
(48, 48)
Progreso: 79/416 18.99%
Error
Progreso: 80/416 19.23%
(48, 48)
Progreso: 81/416 19.47%
(48, 48)
Progreso: 82/416 19.71%
Error
Progreso: 83/416 19.95%
Error
Progreso: 84/416 20.19%
Error
Progreso: 85/416 20.43%
Error
Progreso: 86/416 20.67%
Error
Progreso: 87/416 20.91%
(48, 48)
Progreso: 88/416 21.15%
Error
Progreso: 89/416 21.39%
Error
Progreso: 90/416 21.63%
Error
Progreso: 91/416 21.88%
Error
Progreso: 92/416 22.12%
Error
Progreso: 93/416 22.36%
Error
Progreso: 94/416 22.60%
(48, 48)
Progreso: 95/416 22.84%
Error
Progreso: 96/416 23.08%
(48, 48)
Progreso: 97/416 23.32%
(48, 48)
Progreso: 98/416 23.56%
(48, 48)
Progreso: 99/416 23.80%
Error
Progreso: 100/416 24.04%
(48, 48)
Progreso: 101/416 24.28%
(48, 48)
Progreso: 102/416 24.52%
Error
Progreso: 103/416 24.76%
Error
Progreso: 104/416 25.00%
(48, 48)
Progreso: 105/416 25.24%
(48, 48)
Progreso: 106/416 25.48%
(48, 48)
Progreso: 107/416 25.72%
Error
Progreso: 108/416 25.96%
Error
Progreso: 109/416 26.20%
(48, 48)
Progreso: 110/416 26.44%
Error
Progreso: 111/416 26.68%
Error
Progreso: 112/416 26.92%
(48, 48)
Progreso: 113/416 27.16%
(48, 48)
Progreso: 114/416 27.40%
Error
Progreso: 115/416 27.64%
Error
Progreso: 116/416 27.88%
(48, 48)
Progreso: 117/416 28.12%
Error
Progreso: 118/416 28.37%
(48, 48)
Progreso: 119/416 28.61%
Error
Progreso: 120/416 28.85%
(48, 48)
Progreso: 121/416 29.09%
Error
Progreso: 122/416 29.33%
Error
Progreso: 123/416 29.57%
Error
Progreso: 124/416 29.81%
Error
Progreso: 125/416 30.05%
Error
Progreso: 126/416 30.29%
Error
Progreso: 127/416 30.53%
Error
Progreso: 128/416 30.77%
Error
Progreso: 129/416 31.01%
Error
Progreso: 130/416 31.25%
Error
Progreso: 131/416 31.49%
Error
Progreso: 132/416 31.73%
(48, 48)
Progreso: 133/416 31.97%
(48, 48)
Progreso: 134/416 32.21%
(48, 48)
Progreso: 135/416 32.45%
Error
Progreso: 136/416 32.69%
(48, 48)
Progreso: 137/416 32.93%
(48, 48)
Progreso: 138/416 33.17%
(48, 48)
Progreso: 139/416 33.41%
Error
Progreso: 140/416 33.65%
Error
Progreso: 141/416 33.89%
(48, 48)
Progreso: 142/416 34.13%
Error
Progreso: 143/416 34.38%
(48, 48)
Progreso: 144/416 34.62%
(48, 48)
Progreso: 145/416 34.86%
(48, 48)
Progreso: 146/416 35.10%
(48, 48)
Progreso: 147/416 35.34%
Error
Progreso: 148/416 35.58%
Error
Progreso: 149/416 35.82%
(48, 48)
Progreso: 150/416 36.06%
Error
Progreso: 151/416 36.30%
Error
Progreso: 152/416 36.54%
(48, 48)
Progreso: 153/416 36.78%
Error
Progreso: 154/416 37.02%
(48, 48)
Progreso: 155/416 37.26%
(48, 48)
Progreso: 156/416 37.50%
(48, 48)
Progreso: 157/416 37.74%
(48, 48)
Progreso: 158/416 37.98%
Error
Progreso: 159/416 38.22%
(48, 48)
Progreso: 160/416 38.46%
Error
Progreso: 161/416 38.70%
Error
Progreso: 162/416 38.94%
Error
Progreso: 163/416 39.18%
Error
Progreso: 164/416 39.42%
(48, 48)
Progreso: 165/416 39.66%
(48, 48)
Progreso: 166/416 39.90%
Error
Progreso: 167/416 40.14%
(48, 48)
Progreso: 168/416 40.38%
Error
Progreso: 169/416 40.62%
(48, 48)
Progreso: 170/416 40.87%
Error
Progreso: 171/416 41.11%
Error
Progreso: 172/416 41.35%
(48, 48)
Progreso: 173/416 41.59%
Error
Progreso: 174/416 41.83%
Error
Progreso: 175/416 42.07%
(48, 48)
Progreso: 176/416 42.31%
Error
Progreso: 177/416 42.55%
Error
Progreso: 178/416 42.79%
(48, 48)
Progreso: 179/416 43.03%
(48, 48)
Progreso: 180/416 43.27%
Error
Progreso: 181/416 43.51%
Error
Progreso: 182/416 43.75%
Error
Progreso: 183/416 43.99%
Error
Progreso: 184/416 44.23%
Error
Progreso: 185/416 44.47%
(48, 48)
Progreso: 186/416 44.71%
Error
Progreso: 187/416 44.95%
(48, 48)
Progreso: 188/416 45.19%
(48, 48)
Progreso: 189/416 45.43%
Error
Progreso: 190/416 45.67%
Error
Progreso: 191/416 45.91%
(48, 48)
Progreso: 192/416 46.15%
Error
Progreso: 193/416 46.39%
Error
Progreso: 194/416 46.63%
(48, 48)
Progreso: 195/416 46.88%
Error
Progreso: 196/416 47.12%
(48, 48)
Progreso: 197/416 47.36%
Error
Progreso: 198/416 47.60%
Error
Progreso: 199/416 47.84%
(48, 48)
Progreso: 200/416 48.08%
Error
Progreso: 201/416 48.32%
(48, 48)
Progreso: 202/416 48.56%
Error
Progreso: 203/416 48.80%
(48, 48)
Progreso: 204/416 49.04%
Error
Progreso: 205/416 49.28%
Error
Progreso: 206/416 49.52%
Error
Progreso: 207/416 49.76%
(48, 48)
Progreso: 208/416 50.00%
Error
Progreso: 209/416 50.24%
(48, 48)
Progreso: 210/416 50.48%
(48, 48)
Progreso: 211/416 50.72%
Error
Progreso: 212/416 50.96%
Error
Progreso: 213/416 51.20%
(48, 48)
Progreso: 214/416 51.44%
Error
Progreso: 215/416 51.68%
(48, 48)
Progreso: 216/416 51.92%
Error
Progreso: 217/416 52.16%
(48, 48)
Progreso: 218/416 52.40%
(48, 48)
Progreso: 219/416 52.64%
(48, 48)
Progreso: 220/416 52.88%
(48, 48)
Progreso: 221/416 53.12%
Error
Progreso: 222/416 53.37%
Error
Progreso: 223/416 53.61%
(48, 48)
Progreso: 224/416 53.85%
Error
Progreso: 225/416 54.09%
(48, 48)
Progreso: 226/416 54.33%
(48, 48)
Progreso: 227/416 54.57%
Error
Progreso: 228/416 54.81%
(48, 48)
Progreso: 229/416 55.05%
(48, 48)
Progreso: 230/416 55.29%
(48, 48)
Progreso: 231/416 55.53%
Error
Progreso: 232/416 55.77%
(48, 48)
Progreso: 233/416 56.01%
(48, 48)
Progreso: 234/416 56.25%
(48, 48)
Progreso: 235/416 56.49%
Error
Progreso: 236/416 56.73%
Error
Progreso: 237/416 56.97%
Error
Progreso: 238/416 57.21%
Error
Progreso: 239/416 57.45%
Error
Progreso: 240/416 57.69%
Error
Progreso: 241/416 57.93%
Error
Progreso: 242/416 58.17%
Error
Progreso: 243/416 58.41%
(48, 48)
Progreso: 244/416 58.65%
Error
Progreso: 245/416 58.89%
(48, 48)
Progreso: 246/416 59.13%
(48, 48)
Progreso: 247/416 59.38%
(48, 48)
Progreso: 248/416 59.62%
(48, 48)
Progreso: 249/416 59.86%
(48, 48)
Progreso: 250/416 60.10%
(48, 48)
Progreso: 251/416 60.34%
(48, 48)
Progreso: 252/416 60.58%
(48, 48)
Progreso: 253/416 60.82%
Error
Progreso: 254/416 61.06%
Error
Progreso: 255/416 61.30%
Error
Progreso: 256/416 61.54%
Error
Progreso: 257/416 61.78%
Error
Progreso: 258/416 62.02%
Error
Progreso: 259/416 62.26%
Error
Progreso: 260/416 62.50%
(48, 48)
Progreso: 261/416 62.74%
Error
Progreso: 262/416 62.98%
(48, 48)
Progreso: 263/416 63.22%
(48, 48)
Progreso: 264/416 63.46%
Error
Progreso: 265/416 63.70%
(48, 48)
Progreso: 266/416 63.94%
Error
Progreso: 267/416 64.18%
Error
Progreso: 268/416 64.42%
(48, 48)
Progreso: 269/416 64.66%
(48, 48)
Progreso: 270/416 64.90%
(48, 48)
Progreso: 271/416 65.14%
Error
Progreso: 272/416 65.38%
Error
Progreso: 273/416 65.62%
(48, 48)
Progreso: 274/416 65.87%
Error
Progreso: 275/416 66.11%
Error
Progreso: 276/416 66.35%
Error
Progreso: 277/416 66.59%
(48, 48)
Progreso: 278/416 66.83%
Error
Progreso: 279/416 67.07%
(48, 48)
Progreso: 280/416 67.31%
(48, 48)
Progreso: 281/416 67.55%
(48, 48)
Progreso: 282/416 67.79%
(48, 48)
Progreso: 283/416 68.03%
Error
Progreso: 284/416 68.27%
Error
Progreso: 285/416 68.51%
(48, 48)
Progreso: 286/416 68.75%
Error
Progreso: 287/416 68.99%
(48, 48)
Progreso: 288/416 69.23%
(48, 48)
Progreso: 289/416 69.47%
Error
Progreso: 290/416 69.71%
(48, 48)
Progreso: 291/416 69.95%
(48, 48)
Progreso: 292/416 70.19%
(48, 48)
Progreso: 293/416 70.43%
Error
Progreso: 294/416 70.67%
Error
Progreso: 295/416 70.91%
Error
Progreso: 296/416 71.15%
(48, 48)
Progreso: 297/416 71.39%
(48, 48)
Progreso: 298/416 71.63%
Error
Progreso: 299/416 71.88%
(48, 48)
Progreso: 300/416 72.12%
(48, 48)
Progreso: 301/416 72.36%
(48, 48)
Progreso: 302/416 72.60%
(48, 48)
Progreso: 303/416 72.84%
Error
Progreso: 304/416 73.08%
Error
Progreso: 305/416 73.32%
Error
Progreso: 306/416 73.56%
Error
Progreso: 307/416 73.80%
(48, 48)
Progreso: 308/416 74.04%
Error
Progreso: 309/416 74.28%
Error
Progreso: 310/416 74.52%
Error
Progreso: 311/416 74.76%
(48, 48)
Progreso: 312/416 75.00%
Error
Progreso: 313/416 75.24%
Error
Progreso: 314/416 75.48%
Error
Progreso: 315/416 75.72%
Error
Progreso: 316/416 75.96%
(48, 48)
Progreso: 317/416 76.20%
Error
Progreso: 318/416 76.44%
(48, 48)
Progreso: 319/416 76.68%
Error
Progreso: 320/416 76.92%
(48, 48)
Progreso: 321/416 77.16%
Error
Progreso: 322/416 77.40%
Error
Progreso: 323/416 77.64%
Error
Progreso: 324/416 77.88%
(48, 48)
Progreso: 325/416 78.12%
(48, 48)
Progreso: 326/416 78.37%
Error
Progreso: 327/416 78.61%
Error
Progreso: 328/416 78.85%
(48, 48)
Progreso: 329/416 79.09%
Error
Progreso: 330/416 79.33%
Error
Progreso: 331/416 79.57%
(48, 48)
Progreso: 332/416 79.81%
(48, 48)
Progreso: 333/416 80.05%
(48, 48)
Progreso: 334/416 80.29%
Error
Progreso: 335/416 80.53%
(48, 48)
Progreso: 336/416 80.77%
(48, 48)
Progreso: 337/416 81.01%
(48, 48)
Progreso: 338/416 81.25%
Error
Progreso: 339/416 81.49%
Error
Progreso: 340/416 81.73%
Error
Progreso: 341/416 81.97%
Error
Progreso: 342/416 82.21%
(48, 48)
Progreso: 343/416 82.45%
Error
Progreso: 344/416 82.69%
Error
Progreso: 345/416 82.93%
Error
Progreso: 346/416 83.17%
Error
Progreso: 347/416 83.41%
Error
Progreso: 348/416 83.65%
(48, 48)
Progreso: 349/416 83.89%
Error
Progreso: 350/416 84.13%
Error
Progreso: 351/416 84.38%
(48, 48)
Progreso: 352/416 84.62%
Error
Progreso: 353/416 84.86%
(48, 48)
Progreso: 354/416 85.10%
(48, 48)
Progreso: 355/416 85.34%
Error
Progreso: 356/416 85.58%
Error
Progreso: 357/416 85.82%
Error
Progreso: 358/416 86.06%
Error
Progreso: 359/416 86.30%
Error
Progreso: 360/416 86.54%
(48, 48)
Progreso: 361/416 86.78%
(48, 48)
Progreso: 362/416 87.02%
Error
Progreso: 363/416 87.26%
Error
Progreso: 364/416 87.50%
(48, 48)
Progreso: 365/416 87.74%
Error
Progreso: 366/416 87.98%
Error
Progreso: 367/416 88.22%
Error
Progreso: 368/416 88.46%
Error
Progreso: 369/416 88.70%
Error
Progreso: 370/416 88.94%
Error
Progreso: 371/416 89.18%
(48, 48)
Progreso: 372/416 89.42%
Error
Progreso: 373/416 89.66%
(48, 48)
Progreso: 374/416 89.90%
Error
Progreso: 375/416 90.14%
Error
Progreso: 376/416 90.38%
(48, 48)
Progreso: 377/416 90.62%
Error
Progreso: 378/416 90.87%
Error
Progreso: 379/416 91.11%
(48, 48)
Progreso: 380/416 91.35%
(48, 48)
Progreso: 381/416 91.59%
(48, 48)
Progreso: 382/416 91.83%
Error
Progreso: 383/416 92.07%
(48, 48)
Progreso: 384/416 92.31%
Error
Progreso: 385/416 92.55%
Error
Progreso: 386/416 92.79%
Error
Progreso: 387/416 93.03%
(48, 48)
Progreso: 388/416 93.27%
Error
Progreso: 389/416 93.51%
(48, 48)
Progreso: 390/416 93.75%
Error
Progreso: 391/416 93.99%
Error
Progreso: 392/416 94.23%
(48, 48)
Progreso: 393/416 94.47%
(48, 48)
Progreso: 394/416 94.71%
Error
Progreso: 395/416 94.95%
(48, 48)
Progreso: 396/416 95.19%
Error
Progreso: 397/416 95.43%
Error
Progreso: 398/416 95.67%
(48, 48)
Progreso: 399/416 95.91%
(48, 48)
Progreso: 400/416 96.15%
(48, 48)
Progreso: 401/416 96.39%
Error
Progreso: 402/416 96.63%
(48, 48)
Progreso: 403/416 96.88%
Error
Progreso: 404/416 97.12%
Error
Progreso: 405/416 97.36%
Error
Progreso: 406/416 97.60%
(48, 48)
Progreso: 407/416 97.84%
Error
Progreso: 408/416 98.08%
Error
Progreso: 409/416 98.32%
Error
Progreso: 410/416 98.56%
Error
Progreso: 411/416 98.80%
(48, 48)
Progreso: 412/416 99.04%
Error
Progreso: 413/416 99.28%
(48, 48)
Progreso: 414/416 99.52%
Error
Progreso: 415/416 99.76%
Error
Progreso: 416/416 100.00%
Total: 182

**Comment by manthanSoriya** [comment]
@immanikant  were you successful in solving this error?

**Comment by manthanSoriya** [comment]
I am getting almost similar error




Progreso: 35874/35887 99.96%
(48, 48)
Progreso: 35875/35887 99.97%
(48, 48)
Progreso: 35876/35887 99.97%
(48, 48)
Progreso: 35877/35887 99.97%
Error
Progreso: 35878/35887 99.97%
Error
Progreso: 35879/35887 99.98%
Error
Progreso: 35880/35887 99.98%
Error
Progreso: 35881/35887 99.98%
Error
Progreso: 35882/35887 99.99%
Error
Progreso: 35883/35887 99.99%
Error
Progreso: 35884/35887 99.99%
Error
Progreso: 35885/35887 99.99%
(48, 48)
Progreso: 35886/35887 100.00%
(48, 48)
Progreso: 35887/35887 100.00%
Total: 13974

**Comment by isseu** [comment]
Code was updated, and should work now
