### ISSUE TITLE
Help - Dataset Access

### ISSUE THREAD

**Issue by Gurugoldberg** [isseu/emotion-recognition-neural-networks#41]
Hello,

I'm testing your code.
But I stopped initially in obtaining the
fer2013 dataset

I already signed up for kagler but I did not find this dataset.

Do you have a link that helps me find it?

**Comment by xhjcxxl** [comment]
you want to find this file , you can search it on the baidu or google, then you will found it.

**Comment by isseu** [comment]
Is in the Kaggle link.. https://www.kaggle.com/c/challenges-in-representation-learning-facial-expression-recognition-challenge/data
