### ISSUE TITLE
Is trained network available

### ISSUE THREAD

**Issue by elfadly** [isseu/emotion-recognition-neural-networks#5]
I have a dekstop with no GPU, so training take a lot of time, Do you have the network you trained to be able to run the code

thanks

**Comment by sakshamjindal07** [comment]
I also need one. Please provide if anybody has one.

**Comment by elfadly** [comment]
you can use the network I trained on my CPU available on 
https://github.com/elfadly/CNN-with-tensorflow-for-emotion-recognition

**Comment by sakshamjindal07** [comment]
Hi @elfadly Thanks a ton ! Could you please help with me integrate you pre-trained network with this code base. Also please let me know a little detail about the architecture. This will really help ! Thanks

**Comment by nimish1512** [comment]
https://github.com/nimish1512/Emotion-recognition-and-prediction
